name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        level: 6
  cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show PHP-CS-Fixer version
      run: docker run --rm oskarstark/php-cs-fixer-ga --version
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga